import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Inter, Roboto, Montserrat, Lato, Fira_Sans } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const roboto = Roboto({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-inter' });
const lato = Lato({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
const firaSans = Fira_Sans({ weight: "400", subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.variable}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
