import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Inter, Roboto, Montserrat, Lato, Fira_Sans, Raleway, Poppins, DM_Sans, Rubik } from 'next/font/google';

const font = Inter({ subsets: ['latin'], variable: '--font-inter' });
// const font = Roboto({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = Montserrat({ subsets: ['latin'], variable: '--font-inter' });
// const font = Lato({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = Fira_Sans({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = Raleway({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = Poppins({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = DM_Sans({ weight: "400", subsets: ['latin'], variable: '--font-inter' });
// const font = Rubik({ weight: "400", subsets: ["latin"], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.variable}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
